CREATE DEFINER=`root`@`localhost` FUNCTION `bucleREPEAT`() RETURNS varchar(50) CHARSET utf8mb4
    DETERMINISTIC
BEGIN

DECLARE i TINYINT UNSIGNED DEFAULT 100;
DECLARE suma INT DEFAULT 0;
	bucleREPEAT:REPEAT
	
		SET SUMA = SUMA + I;
		SET I = I - 2;	
		UNTIL I < 90
	END REPEAT bucleREPEAT;
	RETURN CONCAT("SUMA: ", suma);
END