CREATE DEFINER=`root`@`localhost` FUNCTION `bucleWHILE`() RETURNS varchar(50) CHARSET utf8
BEGIN
DECLARE i TINYINT UNSIGNED DEFAULT 0;
DECLARE suma INT DEFAULT 0;
	bucleWHILE:WHILE i < 100 DO
		SET I = I + 1;	
		SET SUMA = SUMA + I;
	END WHILE bucleWHILE;
	RETURN CONCAT("SUMA: ", suma);
END