DROP PROCEDURE IF EXISTS ERROR1;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `ERROR1`(P_ID INT, P_ALUMNO VARCHAR(30))
    MODIFIES SQL DATA
BEGIN

    INSERT INTO ALUMNOS VALUES (P_ID, P_ALUMNO);

END