
DROP PROCEDURE IF EXISTS ERROR8;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `ERROR8`()
BEGIN

DECLARE TABLA_EXISTENTE_ERROR CONDITION FOR 1050;
DECLARE EXIT HANDLER FOR TABLA_EXISTENTE_ERROR
    SELECT ('Fin del programa. La tabla que intentas crear ya existe') 
        AS 'Aviso de error';
    CREATE TABLE ALUMNOS(campo1 INTEGER);
END