CREATE FUNCTION `primeros20Impares`() RETURNS varchar(250)
deterministic
BEGIN

DECLARE CONTADOR,IMPAR INT DEFAULT 1;
DECLARE R VARCHAR(250) DEFAULT concat(' Primeros 20 números impares: ',impar);

IMPARES: LOOP
 IF CONTADOR = 20 THEN
	LEAVE IMPARES;
 ELSE
	SET IMPAR = IMPAR + 2;
	SET R = CONCAT(R,' ', IMPAR);
	
	SET CONTADOR = CONTADOR + 1;
 END IF;
 END LOOP;
 RETURN R;
END
