USE TEST;

DROP PROCEDURE IF EXISTS F1;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `F1`(INOUT P_NUM DECIMAL(12,2))
BEGIN
    IF P_NUM >=0 THEN
        SET P_NUM = FUNCION3(2,P_NUM);
    END IF;
END