USE KADOO;

DROP FUNCTION IF EXISTS FUNCION7;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `FUNCION7`(P_ID INT) RETURNS varchar(30) CHARSET latin1
BEGIN
    DECLARE V_NOMBRE VARCHAR(30);
    SELECT NOMEM
    INTO V_NOMBRE
    FROM TEMPLE
    WHERE NUMEM=P_ID;
    
    RETURN (V_NOMBRE);
END