USE TEST;

DROP FUNCTION IF EXISTS FUNCION1;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `FUNCION1`(P_PESETAS DECIMAL(12,2)) RETURNS decimal(10,2)
deterministic
BEGIN
    RETURN (P_PESETAS / 166.386);
END