USE TEST;
DROP FUNCTION IF EXISTS FUNCION3;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `FUNCION3`(P_MONEDA TINYINT ,P_PESETAS DECIMAL(12,2)) RETURNS decimal(10,2)
BEGIN

DECLARE V_RESULTADO DECIMAL(12,2);

IF P_MONEDA = 1 THEN -- PESETAS --> EUROS
    SET V_RESULTADO =  (P_PESETAS / 166.386);
ELSE    
    SET V_RESULTADO =  (P_PESETAS * 166.386);
END IF;
RETURN V_RESULTADO;
END