USE TEST;
DROP FUNCTION IF EXISTS FUNCION2;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `FUNCION2`(P_MONEDA TINYINT ,P_PESETAS DECIMAL(12,2)) 
RETURNS decimal(10,2)
deterministic
BEGIN
IF P_MONEDA = 1 THEN -- PESETAS --> EUROS
    RETURN (P_PESETAS / 166.386);
ELSE    -- EUROS-->PESETAS
    RETURN (P_PESETAS * 166.386);
END IF;
END