DROP PROCEDURE IF EXISTS ERROR4;

DELIMITER $$

CREATE DEFINER=`root`@`localhost` PROCEDURE `ERROR4`(p_id INT, p_alumno VARCHAR(30), OUT P_RESULTADO VARCHAR(40))
    MODIFIES SQL DATA
BEGIN
    DECLARE CONTINUE HANDLER FOR 1062
    SET P_RESULTADO = CONCAT ('Numero de matricula ', p_id, ' ya existente');
    
    DECLARE CONTINUE HANDLER FOR 1048
    SET P_RESULTADO = CONCAT ('El numero de matricula no puede ser nulo ');

    SET P_RESULTADO = 'CORRECTO';
    INSERT INTO ALUMNOS VALUES (P_ID, P_ALUMNO);

END